//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusKit.ChatNotifications.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusKit.ChatNotifications.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_alliance {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossworld Linkshell 1.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_crosslinkshell1 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.crosslinkshell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossworld Linkshell 2.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_crosslinkshell2 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.crosslinkshell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossworld Linkshell 3.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_crosslinkshell3 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.crosslinkshell3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossworld Linkshell 4.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_crosslinkshell4 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.crosslinkshell4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossworld Linkshell 5.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_crosslinkshell5 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.crosslinkshell5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossworld Linkshell 6.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_crosslinkshell6 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.crosslinkshell6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossworld Linkshell 7.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_crosslinkshell7 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.crosslinkshell7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossworld Linkshell 8.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_crosslinkshell8 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.crosslinkshell8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party (cross-world).
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_crossparty {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.crossparty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Emotes.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_customemote {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.customemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_debug {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_echo {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_freecompany {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.freecompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell 1.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_ls1 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.ls1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell 2.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_ls2 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.ls2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell 3.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_ls3 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.ls3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell 4.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_ls4 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.ls4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell 5.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_ls5 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.ls5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell 6.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_ls6 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.ls6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell 7.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_ls7 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.ls7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell 8.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_ls8 {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.ls8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (silent).
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_none {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_notice {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice Network.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_novicenetwork {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.novicenetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_party {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Team.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_pvpteam {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.pvpteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_say {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shout.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_shout {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.shout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Emotes.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_standardemote {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.standardemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_systemmessage {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.systemmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_tellincoming {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.tellincoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_urgent {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yell.
        /// </summary>
        internal static string nexuskit_chatnotifications_channel_yell {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.channel.yell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string nexuskit_chatnotifications_color {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string nexuskit_chatnotifications_color_blue {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.color.blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string nexuskit_chatnotifications_color_cyan {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.color.cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string nexuskit_chatnotifications_color_default {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.color.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string nexuskit_chatnotifications_color_green {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.color.green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        internal static string nexuskit_chatnotifications_color_grey {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.color.grey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string nexuskit_chatnotifications_color_red {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.color.red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string nexuskit_chatnotifications_color_yellow {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.color.yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notification kinds have been registered yet..
        /// </summary>
        internal static string nexuskit_chatnotifications_empty {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string nexuskit_chatnotifications_enabled {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string nexuskit_chatnotifications_nav {
            get {
                return ResourceManager.GetString("nexuskit.chatnotifications.nav", resourceCulture);
            }
        }
    }
}
