//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusKit.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusKit.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ago.
        /// </summary>
        internal static string nexuskit_time_ago_pattern {
            get {
                return ResourceManager.GetString("nexuskit.time.ago_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d.
        /// </summary>
        internal static string nexuskit_time_days_short {
            get {
                return ResourceManager.GetString("nexuskit.time.days_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h.
        /// </summary>
        internal static string nexuskit_time_hours_short {
            get {
                return ResourceManager.GetString("nexuskit.time.hours_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        internal static string nexuskit_time_just_now {
            get {
                return ResourceManager.GetString("nexuskit.time.just_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m.
        /// </summary>
        internal static string nexuskit_time_minutes_short {
            get {
                return ResourceManager.GetString("nexuskit.time.minutes_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}mo.
        /// </summary>
        internal static string nexuskit_time_months_short {
            get {
                return ResourceManager.GetString("nexuskit.time.months_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}s.
        /// </summary>
        internal static string nexuskit_time_seconds_short {
            get {
                return ResourceManager.GetString("nexuskit.time.seconds_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}w.
        /// </summary>
        internal static string nexuskit_time_weeks_short {
            get {
                return ResourceManager.GetString("nexuskit.time.weeks_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}y.
        /// </summary>
        internal static string nexuskit_time_years_short {
            get {
                return ResourceManager.GetString("nexuskit.time.years_short", resourceCulture);
            }
        }
    }
}
